
["Stargate Journey Client Config"]

	["Stargate Journey Client Config".client]
		#Stargate Journey Client Config
		#Disables smooth animations of Stargate Journey Block Entities
		disable_smooth_animations = false

	["Stargate Journey Client Config"."Stargate Config"]

		["Stargate Journey Client Config"."Stargate Config".client]
			#If true Solar Systems will use unique Symbols
			unique_symbols = false
			#If true Wormholes will produce Vortex after a Kawoosh
			enable_vortex = false
			#Decide if Milky Way Stargate should use the Movie Stargate model
			use_movie_stargate_model = false
			#Decide if Chevrons on the back of Milky Way Stargate should light up
			milky_way_stargate_back_lights_up = false
			#Decide if Chevrons on the back of Pegasus Stargate should light up
			pegasus_stargate_back_lights_up = true
			#If true you will be able to see Stargate Variants
			stargate_variants = true
			#Decide if Event Horizons should be shinier
			shiny_event_horizons = true
			#The amount of distortion the Stargate Event Horizon will experience
			#Range: 0 ~ 25
			event_horizon_distortion = 25
			#If true only the front of the Universe Stargate will rotate
			universe_front_rotates = false
			#Decide if the Primary Chevron on the Movie Stargate model should open
			movie_primary_chevron_opens = false
			#Decide if Movie Stargate model should use alternate chevron locking
			alternate_movie_chevron_locking = false
			#The distance at which the sounds a Stargate makes can still be heard at full volume
			#Range: 0 ~ 128
			stargate_full_sound_distance = 32
			#The distance at which the sounds a Stargate makes can still be heard
			#Range: 16 ~ 128
			stargate_max_sound_distance = 64

	["Stargate Journey Client Config"."DHD Config"]

		["Stargate Journey Client Config"."DHD Config".client]
			#If true, Milky Way DHD symbol positions won't be ordered and instead be based on the canon
			milky_way_dhd_canon_symbol_positions = false
			#If true, Pegasus DHD symbol positions won't be ordered and instead be based on the canon
			pegasus_dhd_canon_symbol_positions = false

	["Stargate Journey Client Config"."Sky Config"]

		["Stargate Journey Client Config"."Sky Config".client]
			#If true you will render a custom Abydos sky
			custom_abydos_sky = true
			#If true you will render a custom Chulak sky
			custom_chulak_sky = true
			#If true you will render a custom Cavum Tenebrae sky
			custom_cavum_tenebrae_sky = true
			#If true you will render a custom Lantea sky
			custom_lantea_sky = true
			#If true you will render a custom Athos sky
			custom_athos_sky = true

