
["Stargate Journey Common Config"]

	["Stargate Journey Common Config".server]
		#Stargate Journey General Config
		#Disable energy requirements for blocks added by Stargate Journey
		disable_energy_requirements = true
		#Stargate Journey ZPM Config
		#The energy that can be extracted from a single level of entropy
		#Range: 1 ~ 9223372036854775807
		zpm_energy_per_level_of_entropy = 100000000000
		#Maximum amount of energy that can be transferred from the ZPM Hub in one tick
		#Range: 1 ~ 9223372036854775807
		zpm_hub_max_transfer = 100000000000
		#Stargate Journey Interface Config
		#The amount of energy a Basic Interface can hold
		#Range: 1 ~ 2147483647
		basic_interface_capacity = 10000000
		#The maximum amount of energy a Basic Interface can transfer at once
		#Range: 1 ~ 2147483647
		basic_interface_max_transfer = 100000
		#The amount of energy a Crystal Interface can hold
		#Range: 1 ~ 2147483647
		crystal_interface_capacity = 100000000
		#The maximum amount of energy a Crystal Interface can transfer at once
		#Range: 1 ~ 2147483647
		crystal_interface_max_transfer = 1000000
		#The amount of energy an Advanced Crystal Interface can hold
		#Range: 1 ~ 2147483647
		advanced_crystal_interface_capacity = 100000000
		#The maximum amount of energy an Advanced Crystal Interface can transfer at once
		#Range: 1 ~ 2147483647
		advanced_crystal_interface_max_transfer = 1000000
		#Stargate Journey Address Config
		#The maximum amount of time the Stargate will be open for in seconds
		#Range: 10 ~ 2280
		max_wormhole_open_time = 228
		#If false, the Wormhole connection can only be ended from the dialing side
		end_connection_from_both_ends = true
		#If true, wormholes can be traveled through both ways
		#Allowed Values: ENABLED, CREATIVE_ONLY, DISABLED
		two_way_wormholes = "CREATIVE_ONLY"
		#If true, going through the wrong side of the wormhole will result in death
		reverse_wormhole_kills = true
		#Enables the use of redstone for manual Stargate dialing
		enable_redstone_dialing = true
		#The maximum connection time can be extended by increasing the energy input
		enable_energy_bypass = false
		#If true, the wormhole will draw power from both connected Stargates
		can_draw_power_from_both_ends = false
		#The amount of energy cost of keeping the wormhole open each tick for system-wide connections
		#Range: 0 ~ 9223372036854775807
		system_wide_connection_energy_draw = 500
		#The amount of energy cost of keeping the wormhole open each tick for interstellar connections
		#Range: 0 ~ 9223372036854775807
		interstellar_connection_energy_draw = 1000
		#The amount of energy cost of keeping the wormhole open each tick for intergalactic connections
		#Range: 0 ~ 9223372036854775807
		intergalactic_connection_energy_draw = 1000000
		#The amount of energy required to estabilish a connection inside a solar system
		#Range: 0 ~ 9223372036854775807
		system_wide_connection_energy_cost = 50000
		#The amount of energy required to estabilish a connection inside the galaxy
		#Range: 0 ~ 9223372036854775807
		interstellar_connection_energy_cost = 100000
		#The amount of energy required to estabilish a connection outside the galaxy
		#Range: 0 ~ 9223372036854775807
		intergalactic_connection_energy_cost = 100000000000
		#The energy required to keep the Stargate open after exceeding the maximum open time is multiplied by this number
		#Range: > 1
		energy_bypass_multiplier = 100000
		#Stargate Journey Energy Config
		#The amount of time in ticks for which the Mark I Naquadah Generator will generate energy from one piece of Weapons Grade Naquadah
		#Range: > 1
		naquadah_generator_mark_i_reaction_time = 100
		#The amount of FE generated per one tick of reaction by the Mark I Naquadah Generator
		#Range: > 1
		naquadah_generator_mark_i_energy_per_tick = 1000
		#The amount of energy a Mark I Naquadah Generator can hold
		#Range: > 1
		naquadah_generator_mark_i_capacity = 10000000
		#The maximum amount of energy a Mark I Naquadah Generator can transfer at once
		#Range: > 1
		naquadah_generator_mark_i_max_transfer = 100000
		#The amount of time in ticks for which the Mark II Naquadah Generator will generate energy from one piece of Weapons Grade Naquadah
		#Range: > 1
		naquadah_generator_mark_ii_reaction_time = 150
		#The amount of FE generated per one tick of reaction by the Mark II Naquadah Generator
		#Range: > 1
		naquadah_generator_mark_ii_energy_per_tick = 1200
		#The amount of energy a Mark II Naquadah Generator can hold
		#Range: > 1
		naquadah_generator_mark_ii_capacity = 100000000
		#The maximum amount of energy a Mark II Naquadah Generator can transfer at once
		#Range: > 1
		naquadah_generator_mark_ii_max_transfer = 1000000
		#Stargate Journey Stargate Network Config
		#Stargate Network will use addresses from datapacks
		use_datapack_addresses = true
		#Stargate Network will generate random addresses for each world.
		generate_random_addresses = true
		#Stargate Network will randomize addresses based on the world seed
		random_addresses_from_seed = false
		#Stargate Journey Tech Config
		#If true Kara Kesh won't require its user to have Naquadah in their bloodstream
		disable_kara_kesh_requirements = true
		#Stargate Journey Genetic Config
		#Percentage of Players who will inherit the Ancient Gene
		#Range: 0 ~ 100
		player_ata_gene_inheritance_chance = 30
		#Percentage of Villagers who will inherit the Ancient Gene
		#Range: 0 ~ 100
		villager_player_ata_gene_inheritance_chance = 30
		#Probability of the Prototype Ancient Gene Therapy working
		#Range: 0 ~ 100
		prototype_ata_gene_therapy_success_rate = 50
		#Probability of the Ancient Gene Therapy working
		#Range: 0 ~ 100
		ata_gene_therapy_success_rate = 100

